name: Python application deployment

on:
  push:
    branches:
      - main  # 确保这里的分支与您的实际分支名匹配

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # 或者你选择的其他版本


    - name: Install system dependencies for pyodbc
      run: sudo apt-get update && sudo apt-get install -y unixodbc-dev gcc g++ 

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'WITWebApp918'  # 你的 Azure Web 应用名称
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # 确保在您的 GitHub 仓库中设置了此密钥
        package: .



